# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: []
        max_age: 3600
    paths:
        '^/': null
